apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: k8spsprunasgroup-init
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  location: "spec.initContainers[name:*].securityContext.runAsGroup"
  parameters:
    pathTests:
    - subPath: "spec.initContainers[name:*].securityContext.runAsGroup"
      condition: MustNotExist
    assign:
      value: 2000
